[workspace]
members = [
  "crates/video-hw-core",
  "crates/video-hw",
  "crates/video-hw-backend-nvidia",
  "crates/video-hw-backend-intel",
  "crates/video-hw-backend-vulkan",
  "crates/video-hw-backend-vt",
]
default-members = ["crates/video-hw"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
