[package]
name = "video-hw-fmp4"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"

[features]
default = []
async-session = ["dep:tokio"]
serde = ["dep:serde"]
unstable-raw-inputs = ["video-hw/unstable-raw-inputs"]
backend-vt = ["video-hw/backend-vt"]
backend-nvidia = ["video-hw/backend-nvidia"]
backend-intel = ["video-hw/backend-intel"]
backend-vulkan = ["video-hw/backend-vulkan"]

[dependencies]
anyhow = "1.0.101"
shiguredo_mp4 = "2026.2.0"
video-hw = { path = "../video-hw", default-features = false }
tokio = { version = "1.50.0", features = ["rt", "sync"], optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }

[dev-dependencies]
clap = { version = "4.5.59", features = ["derive"] }
eframe = "0.33.3"
serde_json = "1.0.149"
shiguredo_video_device = "2026.1.0-canary.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }

[[example]]
name = "camera_record_fmp4_gui"
required-features = ["async-session"]
