[package]
name = "video-hw-backend-vt"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["backend-vt"]
backend-vt = ["video-hw-core/backend-vt"]
unstable-raw-inputs = ["video-hw-core/unstable-raw-inputs"]

[dependencies]
video-hw-core = { path = "../video-hw-core", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { version = "0.10.1" }
core-media = { version = "0.7.1" }
core-video = { version = "0.5.2" }
metal = { version = "0.33.0" }
video-toolbox = { version = "0.2.1" }
